repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: end-of-file-fixer
        files: '\.(py|txt)$' # Only run on .py and .txt files	
    -   id: trailing-whitespace
        files: '\.(py|txt)$' # Only run on .py and .txt files
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.2
    hooks:
    -   id: ruff
        args: [--line-length, '120', --fix, --exit-non-zero-on-fix]
    -   id: ruff-format
        args: [--line-length, '120']
