import warnings
import numpy as np
import pytest
from qtpy.QtCore import Slot

from pydm.tests.conftest import ConnectionSignals
from pydm.widgets.archiver_time_plot import ArchivePlotCurveItem, PyDMArchiverTimePlot, FormulaCurveItem
from pydm.utilities.safe_eval import MAX_DEPENDENCY_DEPTH


@pytest.mark.parametrize("address", ["ca://LINAC:PV1", "pva://LINAC:PV1", "LINAC:PV1"])
def test_set_archive_channel(address):
    """Verify the address for the archiver data plugin is set correctly for all possible EPICS address prefixes"""
    curve_item = ArchivePlotCurveItem(channel_address=address)
    assert curve_item.archive_channel.address == "archiver://pv=LINAC:PV1"


def test_receive_archive_data(signals: ConnectionSignals):
    """Ensure data from archiver appliance is inserted into the archive buffer correctly"""
    curve_item = ArchivePlotCurveItem()
    curve_item.setBufferSize(20)
    curve_item.setArchiveBufferSize(20)

    # We start with a data buffer with some sample values like those generated by a running time plot
    # The x-values are timestamps and the y-values are samples from a PV
    example_live_data = np.array([[100, 101, 102, 103, 104, 105], [2.15, 2.20, 2.25, 2.22, 2.20, 2.18]])
    starting_data = np.concatenate((np.zeros((2, curve_item.getBufferSize() - 6)), example_live_data), axis=1)
    curve_item.points_accumulated += 6
    curve_item.data_buffer = starting_data

    # A quick check to make sure we're starting off correctly
    assert (2, 20) == curve_item.data_buffer.shape

    signals.new_value_signal[np.ndarray].connect(curve_item.receiveArchiveData)

    # First test the most basic case, where we've requested a bit of archive data right before the live data
    mock_archive_data = np.array([[70, 75, 80, 85, 90, 95], [2.05, 2.08, 2.07, 2.08, 2.12, 2.14]])
    signals.new_value_signal[np.ndarray].emit(mock_archive_data)

    expected_data = np.zeros((2, 14))
    expected_data = np.concatenate((expected_data, mock_archive_data), axis=1)

    # Confirm the archive data was inserted as expected
    assert np.array_equal(curve_item.archive_data_buffer, expected_data)


def test_insert_archive_data():
    """When first receiving large amounts of data from the archiver appliance, it will be of the 'optimized' form
    in which it is sampled across a fixed number of bins. Drawing a zoom box in this data will get more detailed
    data which must be inserted into the archive data buffer. This tests that insertion is successful."""
    curve_item = ArchivePlotCurveItem()
    curve_item.setBufferSize(10)
    curve_item.setArchiveBufferSize(10)

    # Need some initial data in the live data buffer so that the archive data gets inserted into the proper place
    curve_item.data_buffer = np.array([[130, 140], [8, 9]])
    curve_item.points_accumulated = 2

    # Set up a sample archive buffer
    curve_item.archive_data_buffer = np.array(
        [[0, 0, 0, 0, 100, 105, 110, 115, 120, 125], [0, 0, 0, 0, 2, 3, 4, 5, 6, 7]], dtype=float
    )

    curve_item.archive_points_accumulated = 6
    curve_item.zoomed = True

    # Receive raw data that is more detailed than the two values it will be replacing
    mock_archive_data = np.array([[104, 106, 108, 111], [2.8, 3.1, 3.7, 3.95]])

    curve_item.insert_archive_data(mock_archive_data)

    # The original average values for timestamps 105 and 106 should now be replace with the actual PV data
    expected_data = np.array([[0, 0, 100, 104, 106, 108, 111, 115, 120, 125], [0, 0, 2, 2.8, 3.1, 3.7, 3.95, 5, 6, 7]])

    assert np.array_equal(curve_item.archive_data_buffer, expected_data)


def test_archive_buffer_full():
    """If we insert more data points than the archive buffer can hold, then the oldest points are
    removed in favor of the new ones until the user requests further backfill data again"""
    curve_item = ArchivePlotCurveItem()
    curve_item.setBufferSize(6)
    curve_item.setArchiveBufferSize(6)
    curve_item.data_buffer = np.array([[130, 140], [8, 9]])
    curve_item.points_accumulated = 2

    # Set up a sample archive buffer that is already full
    curve_item.archive_data_buffer = np.array([[100, 105, 110, 115, 120, 125], [2, 3, 4, 5, 6, 7]], dtype=float)
    curve_item.archive_points_accumulated = 6
    curve_item.zoomed = True

    # Receive data that will cause that will not fit in the buffer without deleting other data points
    mock_archive_data = np.array([[104, 106, 108], [2.8, 3.1, 3.7]])

    curve_item.insert_archive_data(mock_archive_data)

    # This is what is left over after the oldest data points have been trimmed
    expected_data = np.array([[104, 106, 108, 115, 120, 125], [2.8, 3.1, 3.7, 5, 6, 7]])

    assert np.array_equal(curve_item.archive_data_buffer, expected_data)


@Slot(float, float, str)
def inspect_data_request(min_x: float, max_x: float, processing_command: str):
    """Simple helper function to store the signal parameters it was invoked with"""
    inspect_data_request.min_x = min_x
    inspect_data_request.max_x = max_x
    inspect_data_request.processing_command = processing_command


def test_request_data_from_archiver(qtbot):
    """Test that the signal requesting data from the archiver appliance is built correctly"""

    # Create a plot and its associated curve item
    plot = PyDMArchiverTimePlot(optimized_data_bins=10)
    curve_item = ArchivePlotCurveItem()
    # Connect to the helper function above to allow for inspection of the parameters the signal was invoked with
    curve_item.archive_data_request_signal.connect(inspect_data_request)
    plot._curves.append(curve_item)

    # Request data from a short 100 second period
    plot._archive_request_queued = True
    plot.requestDataFromArchiver(100, 200)

    # Verify that the data is requested for the time period specified, and since it is only 100 seconds, it is raw data
    assert inspect_data_request.min_x == 100
    assert inspect_data_request.max_x == 199
    assert inspect_data_request.processing_command == ""

    # Now request over a day's worth of data at once. This will cause the request to be for optimized data
    # returned in 10 bins as specified by the "optimized_data_bins" param above
    plot._archive_request_queued = True
    plot.requestDataFromArchiver(100, 100000)
    assert inspect_data_request.min_x == 100
    assert inspect_data_request.max_x == 99999
    assert inspect_data_request.processing_command == "optimized_10"

    # Finally let's do a test without specifying min_x and max_x to test the plot's logic of determining
    # these values itself

    # Create a small data buffer for the plot's curve representing live data visible on the plot
    curve_item.points_accumulated = 3
    curve_item._bufferSize = 5
    # Index 0 represents timestamps, index 1 the associated values. So observations were made at time 300, 301, 302.
    curve_item.data_buffer = np.array([[0, 0, 300, 301, 302], [0, 0, 1.5, 1.6, 1.5]])

    plot._min_x = 50  # This is the minimum timestamp visible on the x-axis, representing what the user panned to
    plot._archive_request_queued = True
    plot.requestDataFromArchiver()
    # The min_x requested should have defaulted to 50 since that is what the user requested as mentioned above
    assert inspect_data_request.min_x == 50
    # Because the oldest live timestamp in the data buffer was 300, the ending timestamp for the request should
    # be one less than that.
    assert inspect_data_request.max_x == 299


# ------------------------------------------------------------------ #
#  Computed ArchivePlotCurveItem (formula) tests                       #
# ------------------------------------------------------------------ #


def _make_connected_curve(archive_data, archive_points=None):
    """Helper to create a connected ArchivePlotCurveItem with archive data."""
    curve = ArchivePlotCurveItem()
    curve.archive_data_buffer = np.array(archive_data, dtype=float)
    curve.archive_points_accumulated = archive_points if archive_points is not None else len(archive_data[0])
    curve.connected = True
    curve.arch_connected = True
    return curve


def test_computed_curve_is_computed():
    """Verify is_computed returns True for formula curves and False for normal curves."""
    normal = ArchivePlotCurveItem()
    assert normal.is_computed is False

    curve1 = _make_connected_curve([[100, 105], [2, 3]])
    computed = ArchivePlotCurveItem(formula=r"f://5*{A}", pvs={"A": curve1})
    assert computed.is_computed is True


def test_computed_curve_no_channel():
    """Verify computed curves do not create archiver channels."""
    curve1 = _make_connected_curve([[100, 105], [2, 3]])
    computed = ArchivePlotCurveItem(formula=r"f://5*{A}", pvs={"A": curve1})
    channels = computed.channels()
    assert channels == [None]


def test_computed_curve_formula_property():
    """Verify the formula property returns the original formula string."""
    curve1 = _make_connected_curve([[100, 105], [2, 3]])
    computed = ArchivePlotCurveItem(formula=r"f://5*{A}", pvs={"A": curve1})
    assert computed.formula == r"f://5*{A}"


def test_computed_curve_evaluate_multiplication():
    """Test a simple multiplication formula: 5*A."""
    curve1 = _make_connected_curve([[100, 105, 110, 115, 120, 125], [2, 3, 4, 5, 6, 7]])

    computed = ArchivePlotCurveItem(formula=r"f://5*{A}", pvs={"A": curve1})
    computed.evaluate()

    expected = np.array([[100, 105, 110, 115, 120, 125], [10, 15, 20, 25, 30, 35]], dtype=float)
    assert np.array_equal(computed.archive_data_buffer, expected)


def test_computed_curve_evaluate_log():
    """Test a log formula: log(A)."""
    curve1 = _make_connected_curve([[100, 105, 110, 115, 120, 125], [2, 3, 4, 5, 6, 7]])

    computed = ArchivePlotCurveItem(formula=r"f://log({A})", pvs={"A": curve1})
    computed.evaluate()

    expected = np.array([[100, 105, 110, 115, 120, 125], np.log([2, 3, 4, 5, 6, 7])], dtype=float)
    assert np.array_equal(computed.archive_data_buffer, expected)


def test_computed_curve_evaluate_addition_two_pvs():
    """Test adding two PVs: A + B with different timestamp grids."""
    curve1 = _make_connected_curve([[100, 105, 110, 115, 120, 125], [2, 3, 4, 5, 6, 7]])
    curve2 = _make_connected_curve([[101, 106, 111, 116, 121, 126], [1, 2, 3, 4, 5, 6]])

    computed = ArchivePlotCurveItem(formula=r"f://{A}+{B}", pvs={"A": curve1, "B": curve2})
    computed.evaluate()

    expected = np.array(
        [[101, 105, 106, 110, 111, 115, 116, 120, 121, 125], [3, 4, 5, 6, 7, 8, 9, 10, 11, 12]], dtype=float
    )
    assert np.array_equal(computed.archive_data_buffer, expected)


def test_computed_curve_evaluate_multiplication_two_pvs():
    """Test multiplying two PVs: A * B with different timestamp grids."""
    curve1 = _make_connected_curve([[100, 105, 110, 115, 120, 125], [2, 3, 4, 5, 6, 7]])
    curve2 = _make_connected_curve([[101, 106, 111, 116, 121, 126], [1, 2, 3, 4, 5, 6]])

    computed = ArchivePlotCurveItem(formula=r"f://{A}*{B}", pvs={"A": curve1, "B": curve2})
    computed.evaluate()

    expected = np.array(
        [[101, 105, 106, 110, 111, 115, 116, 120, 121, 125], [2, 3, 6, 8, 12, 15, 20, 24, 30, 35]], dtype=float
    )
    assert np.array_equal(computed.archive_data_buffer, expected)


def test_computed_curve_safe_eval_blocks_dangerous():
    """Verify that dangerous expressions raise errors instead of executing."""
    curve1 = _make_connected_curve([[100, 105], [2, 3]])

    # __import__ should be blocked by SafeExpressionEvaluator
    computed = ArchivePlotCurveItem(formula=r"f://__import__('os')", pvs={"A": curve1})
    # The evaluation should fail safely — the formula_invalid_signal should be emitted
    # and archive_data_buffer should remain empty
    computed.evaluate()
    assert computed.archive_data_buffer.shape[1] == 0


def test_computed_curve_disconnected_dependencies():
    """When a dependency is disconnected, the computed curve should produce no data."""
    connected_curve = _make_connected_curve([[100, 105, 110, 115, 120, 125], [2, 3, 4, 5, 6, 7]])

    disconnected_curve = ArchivePlotCurveItem()
    disconnected_curve.archive_data_buffer = np.array(
        [[101, 106, 111, 116, 121, 126], [1, 2, 3, 4, 5, 6]], dtype=float
    )
    disconnected_curve.archive_points_accumulated = 6
    disconnected_curve.connected = False
    disconnected_curve.arch_connected = False

    formula = r"f://{A}+{B}"
    computed = ArchivePlotCurveItem(formula=formula, pvs={"A": connected_curve, "B": disconnected_curve})
    computed.evaluate()

    # Should have no data since B is disconnected
    assert np.array_equal(computed.archive_data_buffer, np.zeros((2, 0), dtype=float))


def test_computed_curve_disconnected_formula_dependency():
    """When a formula dependency is disconnected, the parent computed curve should produce no data."""
    connected_curve = _make_connected_curve([[100, 105, 110, 115, 120, 125], [2, 3, 4, 5, 6, 7]])

    # Create a disconnected computed curve (formula with empty formula)
    disconnected_formula = ArchivePlotCurveItem(formula="f://0")
    disconnected_formula.archive_data_buffer = np.array(
        [[101, 106, 111, 116, 121, 126], [1, 2, 3, 4, 5, 6]], dtype=float
    )
    disconnected_formula.archive_points_accumulated = 6
    disconnected_formula.connected = False
    disconnected_formula.arch_connected = False

    formula = r"f://{A}+{B}"
    computed = ArchivePlotCurveItem(formula=formula, pvs={"A": connected_curve, "B": disconnected_formula})
    computed.evaluate()

    # Should have no data since B is disconnected
    assert np.array_equal(computed.archive_data_buffer, np.zeros((2, 0), dtype=float))


# ------------------------------------------------------------------ #
#  Circular dependency detection tests                                 #
# ------------------------------------------------------------------ #


def test_circular_dependency_direct():
    """A formula that references itself should be detected by _detect_cycle."""
    curve_a = _make_connected_curve([[100, 105], [2, 3]])
    # Test _detect_cycle static method directly: curve_a depending on itself is a cycle
    assert ArchivePlotCurveItem._detect_cycle(curve_a, {"A": curve_a}) is True


def test_circular_dependency_indirect():
    """A -> B -> A chain should be detected."""
    curve_a = _make_connected_curve([[100, 105], [2, 3]])
    curve_b = ArchivePlotCurveItem(formula=r"f://5*{A}", pvs={"A": curve_a})

    # Now try to make A depend on B — that would create a cycle
    assert ArchivePlotCurveItem._detect_cycle(curve_a, {"B": curve_b}) is True


def test_circular_dependency_deep_chain():
    """A -> B -> C -> A chain should be detected."""
    curve_a = _make_connected_curve([[100, 105], [2, 3]])
    curve_b = ArchivePlotCurveItem(formula=r"f://5*{A}", pvs={"A": curve_a})
    curve_c = ArchivePlotCurveItem(formula=r"f://5*{B}", pvs={"B": curve_b})

    # Now try to make A depend on C — that would create a cycle
    assert ArchivePlotCurveItem._detect_cycle(curve_a, {"C": curve_c}) is True


def test_no_circular_dependency():
    """A valid chain: A -> B should not be flagged as circular."""
    curve_a = _make_connected_curve([[100, 105], [2, 3]])
    curve_b = _make_connected_curve([[100, 105], [4, 5]])

    # C depends on both A and B — no cycle
    assert ArchivePlotCurveItem._detect_cycle(curve_a, {"B": curve_b}) is False


def test_max_dependency_depth_exceeded():
    """A chain deeper than MAX_DEPENDENCY_DEPTH should be rejected at construction."""
    # Build a chain up to the limit (this succeeds)
    base_curve = _make_connected_curve([[100, 105], [2, 3]])
    current = base_curve
    for i in range(MAX_DEPENDENCY_DEPTH):
        current = ArchivePlotCurveItem(formula=r"f://5*{A}", pvs={"A": current})

    # Adding one more layer should exceed the depth limit and raise ValueError
    with pytest.raises(ValueError, match="maximum depth"):
        ArchivePlotCurveItem(formula=r"f://5*{A}", pvs={"A": current})


def test_dependency_depth_within_limit():
    """A chain within MAX_DEPENDENCY_DEPTH should be allowed."""
    base_curve = _make_connected_curve([[100, 105], [2, 3]])
    current = base_curve
    # Build a chain of depth 3 (well within limit)
    for i in range(3):
        current = ArchivePlotCurveItem(formula=r"f://5*{A}", pvs={"A": current})

    depth = ArchivePlotCurveItem._get_dependency_depth({"A": current})
    assert depth <= MAX_DEPENDENCY_DEPTH


# ------------------------------------------------------------------ #
#  Computed curves skip archiver requests                              #
# ------------------------------------------------------------------ #


def test_request_data_skips_computed_curves(qtbot):
    """Verify that requestDataFromArchiver skips computed curves."""
    plot = PyDMArchiverTimePlot(optimized_data_bins=10)

    # Create a normal curve
    normal_curve = ArchivePlotCurveItem()
    normal_curve.archive_data_request_signal.connect(inspect_data_request)

    # Create a computed curve
    computed_curve = ArchivePlotCurveItem(formula=r"f://5*{A}", pvs={"A": normal_curve})

    plot._curves.append(normal_curve)
    plot._curves.append(computed_curve)

    # Request data — only the normal curve should emit the signal
    plot._archive_request_queued = True
    plot.requestDataFromArchiver(100, 200)

    # The normal curve's signal was emitted
    assert inspect_data_request.min_x == 100
    assert inspect_data_request.max_x == 199


# ------------------------------------------------------------------ #
#  to_dict for computed curves                                         #
# ------------------------------------------------------------------ #


def test_computed_curve_to_dict():
    """Verify to_dict includes formula and curveDict for computed curves."""
    curve1 = _make_connected_curve([[100, 105], [2, 3]])
    curve1.address = "ca://TEST:PV1"

    computed = ArchivePlotCurveItem(formula=r"f://5*{A}", pvs={"A": curve1})
    d = computed.to_dict()

    assert "formula" in d
    assert d["formula"] == r"f://5*{A}"
    assert "curveDict" in d
    assert "A" in d["curveDict"]


# ------------------------------------------------------------------ #
#  Deprecated FormulaCurveItem backward compatibility                   #
# ------------------------------------------------------------------ #


def test_formula_curve_item_deprecated():
    """Verify FormulaCurveItem emits a DeprecationWarning."""
    curve1 = _make_connected_curve([[100, 105, 110, 115, 120, 125], [2, 3, 4, 5, 6, 7]])

    with warnings.catch_warnings(record=True) as w:
        warnings.simplefilter("always")
        fc = FormulaCurveItem(formula=r"f://5*{A}", pvs={"A": curve1})
        assert len(w) == 1
        assert issubclass(w[0].category, DeprecationWarning)
        assert "deprecated" in str(w[0].message).lower()

    # Should still work as a computed curve
    assert fc.is_computed is True


def test_formula_curve_item_backward_compat():
    """Test that FormulaCurveItem still works for the original test scenarios."""
    curve_item1 = _make_connected_curve([[100, 105, 110, 115, 120, 125], [2, 3, 4, 5, 6, 7]])
    curve_item2 = _make_connected_curve([[101, 106, 111, 116, 121, 126], [1, 2, 3, 4, 5, 6]])

    curves1 = {"A": curve_item1}
    curves2 = {"A": curve_item1, "B": curve_item2}

    with warnings.catch_warnings():
        warnings.simplefilter("ignore", DeprecationWarning)
        formula_curve_1 = FormulaCurveItem(formula=r"f://5*{A}", pvs=curves1)
        formula_curve_2 = FormulaCurveItem(formula=r"f://log({A})", pvs=curves1)
        formula_curve_3 = FormulaCurveItem(formula=r"f://{A}+{B}", pvs=curves2)
        formula_curve_4 = FormulaCurveItem(formula=r"f://{A}*{B}", pvs=curves2)

    expected1 = np.array([[100, 105, 110, 115, 120, 125], [10, 15, 20, 25, 30, 35]], dtype=float)
    expected2 = np.array([[100, 105, 110, 115, 120, 125], np.log([2, 3, 4, 5, 6, 7])], dtype=float)
    expected3 = np.array(
        [[101, 105, 106, 110, 111, 115, 116, 120, 121, 125], [3, 4, 5, 6, 7, 8, 9, 10, 11, 12]], dtype=float
    )
    expected4 = np.array(
        [[101, 105, 106, 110, 111, 115, 116, 120, 121, 125], [2, 3, 6, 8, 12, 15, 20, 24, 30, 35]], dtype=float
    )

    formula_curve_1.evaluate()
    formula_curve_2.evaluate()
    formula_curve_3.evaluate()
    formula_curve_4.evaluate()

    assert np.array_equal(formula_curve_1.archive_data_buffer, expected1)
    assert np.array_equal(formula_curve_2.archive_data_buffer, expected2)
    assert np.array_equal(formula_curve_3.archive_data_buffer, expected3)
    assert np.array_equal(formula_curve_4.archive_data_buffer, expected4)


def test_disconnected_formula_curve_item_backward_compat():
    """Test backward compatibility for disconnected FormulaCurveItem."""
    connected_curve = _make_connected_curve([[100, 105, 110, 115, 120, 125], [2, 3, 4, 5, 6, 7]])

    disconnected_curve = ArchivePlotCurveItem()
    disconnected_curve.archive_data_buffer = np.array(
        [[101, 106, 111, 116, 121, 126], [1, 2, 3, 4, 5, 6]], dtype=float
    )
    disconnected_curve.archive_points_accumulated = 6
    disconnected_curve.connected = False
    disconnected_curve.arch_connected = False

    with warnings.catch_warnings():
        warnings.simplefilter("ignore", DeprecationWarning)
        disconnected_formula = FormulaCurveItem(formula="f://0")
    disconnected_formula.archive_data_buffer = np.array(
        [[101, 106, 111, 116, 121, 126], [1, 2, 3, 4, 5, 6]], dtype=float
    )
    disconnected_formula.archive_points_accumulated = 6
    disconnected_formula.connected = False
    disconnected_formula.arch_connected = False

    formula = r"f://{A}+{B}"

    with warnings.catch_warnings():
        warnings.simplefilter("ignore", DeprecationWarning)
        formula_curve_1 = FormulaCurveItem(formula=formula, pvs={"A": connected_curve, "B": disconnected_curve})
        formula_curve_2 = FormulaCurveItem(formula=formula, pvs={"A": connected_curve, "B": disconnected_formula})

    formula_curve_1.evaluate()
    formula_curve_2.evaluate()

    # Both curves should have no data
    assert np.array_equal(formula_curve_1.archive_data_buffer, np.zeros((2, 0), dtype=float))
    assert np.array_equal(formula_curve_2.archive_data_buffer, np.zeros((2, 0), dtype=float))


# ------------------------------------------------------------------ #
#  Editor model tests                                                  #
# ------------------------------------------------------------------ #


def test_editor_get_data_computed_curve():
    """Verify the editor model's get_data returns the formula for computed curves."""
    from pydm.widgets.archiver_time_plot_editor import PyDMArchiverTimePlotCurvesModel

    curve1 = _make_connected_curve([[100, 105], [2, 3]])
    computed = ArchivePlotCurveItem(formula=r"f://5*{A}", pvs={"A": curve1})

    # Create a minimal plot for the model
    plot = PyDMArchiverTimePlot()
    model = PyDMArchiverTimePlotCurvesModel(plot)

    result = model.get_data("Channel", computed)
    assert result == r"f://5*{A}"


def test_editor_get_data_normal_curve():
    """Verify the editor model's get_data returns the address for normal curves."""
    from pydm.widgets.archiver_time_plot_editor import PyDMArchiverTimePlotCurvesModel

    curve = ArchivePlotCurveItem(channel_address="ca://TEST:PV1")
    plot = PyDMArchiverTimePlot()
    model = PyDMArchiverTimePlotCurvesModel(plot)

    result = model.get_data("Channel", curve)
    assert result == "ca://TEST:PV1"
